export const REGISTER_COMPANIES_FORM = "REGISTER_COMPANIES_FORM";
export const REGISTER_COMPANIES_OWNERS_FORM = "REGISTER_COMPANIES_OWNERS_FORM";
export const COMPANIES_OWNERS_RSHIP_FORM = "COMPANIES_OWNERS_RSHIP_FORM";
