export const REGISTER_ACADEMIC_CLASS_LEVELS = "REGISTER_ACADEMIC_CLASS_LEVELS";
export const REGISTER_CLASS_STREAMS = "REGISTER_CLASS_STREAMS";
export const REGISTER_TERM_ITERATIONS = "REGISTER_TERM_ITERATIONS";
export const REGISTER_WEEK_ITERATIONS = "REGISTER_WEEK_ITERATIONS";
export const REGISTER_ACTUAL_TERMS = "REGISTER_ACTUAL_TERMS";
export const REGISTER_ACTUAL_WEEKS = "REGISTER_ACTUAL_WEEKS";
