export const TOGGLE_MODAL_DISPLAY = "TOGGLE_MODAL_DISPLAY";

/* START - ACADEMIC CLASS LEVEL ***************************************************************************************/

export const SETUP_CLASS_LEVEL_FORM = "SETUP_CLASS_LEVEL_FORM";
export const RESET_CURRENT_ACADEMIC_CLASS_LEVEL_CREATED =
  "RESET_CURRENT_ACADEMIC_CLASS_LEVEL_CREATED";

export const BEGIN_CLASS_LEVEL_CREATION = "BEGIN_CLASS_LEVEL_CREATION";
export const CLASS_LEVEL_CREATED_SUCCESSFULLY =
  "CLASS_LEVEL_CREATED_SUCCESSFULLY";
export const CLASS_LEVEL_CREATION_FAILED = "CLASS_LEVEL_CREATION_FAILED";
export const ERROR_OCCURRED_ON_CREATING_CLASS_LEVEL =
  "ERROR_OCCURRED_ON_CREATING_CLASS_LEVEL";

export const START_FETCHING_CLASS_LEVELS = "START_FETCHING_CLASS_LEVELS";
export const FETCHING_CLASS_LEVELS_SUCCESSFUL =
  "FETCHING_CLASS_LEVELS_SUCCESSFUL";
export const FETCHING_CLASS_LEVELS_EMPTY_RESULT_SET =
  "FETCHING_CLASS_LEVELS_EMPTY_RESULT_SET";
export const ERROR_OCCURED_WHILE_FETCHING_CLASS_LEVELS =
  "ERROR_OCCURED_WHILE_FETCHING_CLASS_LEVELS";

/* END - ACADEMIC CLASS LEVEL ***************************************************************************************/

/* START - CLASS STREAMS ***************************************************************************************/

export const BEGIN_CLASS_STREAM_CREATION = "BEGIN_CLASS_STREAM_CREATION";
export const CLASS_STREAM_CREATED_SUCCESSFULLY =
  "CLASS_STREAM_CREATED_SUCCESSFULLY";
export const CLASS_STREAM_CREATION_FAILED = "CLASS_STREAM_CREATION_FAILED";
export const ERROR_OCCURRED_ON_CREATING_CLASS_STREAM =
  "ERROR_OCCURRED_ON_CREATING_CLASS_STREAM";

export const START_FETCHING_CLASS_STREAMS = "START_FETCHING_CLASS_STREAMS";
export const FETCHING_CLASS_STREAMS_SUCCESSFUL =
  "FETCHING_CLASS_STREAMS_SUCCESSFUL";
export const FETCHING_CLASS_STREAMS_EMPTY_RESULT_SET =
  "FETCHING_CLASS_STREAMS_EMPTY_RESULT_SET";
export const ERROR_OCCURED_WHILE_FETCHING_CLASS_STREAMS =
  "ERROR_OCCURED_WHILE_FETCHING_CLASS_STREAMS";

export const RESET_CURRENT_CLASS_STREAM_CREATED =
  "RESET_CURRENT_CLASS_STREAM_CREATED";

export const SETUP_CLASS_STREAM_FORM = "SETUP_CLASS_STREAM_FORM";

/* END - CLASS STREAMS ***************************************************************************************/

/* START - TERM ITERATIONS ***************************************************************************************/

export const START_FETCHING_TERM_ITERATIONS = "START_FETCHING_TERM_ITERATIONS";
export const FETCHING_TERM_ITERATIONS_SUCCESSFUL =
  "FETCHING_TERM_ITERATIONS_SUCCESSFUL";
export const FETCHING_TERM_ITERATIONS_EMPTY_RESULT_SET =
  "FETCHING_TERM_ITERATIONS_EMPTY_RESULT_SET";
export const ERROR_OCCURED_WHILE_FETCHING_TERM_ITERATIONS =
  "ERROR_OCCURED_WHILE_FETCHING_TERM_ITERATIONS";

export const SETUP_TERM_ITERATIONS_FORM = "SETUP_TERM_ITERATIONS_FORM";

export const RESET_CURRENT_TERM_ITERATION_CREATED =
  "RESET_CURRENT_TERM_ITERATION_CREATED";

export const BEGIN_TERM_ITERATION_CREATION = "BEGIN_TERM_ITERATION_CREATION";
export const TERM_ITERATION_CREATED_SUCCESSFULLY =
  "TERM_ITERATION_CREATED_SUCCESSFULLY";
export const TERM_ITERATION_CREATION_FAILED = "TERM_ITERATION_CREATION_FAILED";
export const ERROR_OCCURRED_ON_CREATING_TERM_ITERATION =
  "ERROR_OCCURRED_ON_CREATING_TERM_ITERATION";

/* END - TERM ITERATIONS ***************************************************************************************/

/* START - WEEK ITERATIONS ***************************************************************************************/

export const START_FETCHING_WEEK_ITERATIONS = "START_FETCHING_WEEK_ITERATIONS";
export const FETCHING_WEEK_ITERATIONS_SUCCESSFUL =
  "FETCHING_WEEK_ITERATIONS_SUCCESSFUL";
export const FETCHING_WEEK_ITERATIONS_EMPTY_RESULT_SET =
  "FETCHING_WEEK_ITERATIONS_EMPTY_RESULT_SET";
export const ERROR_OCCURED_WHILE_FETCHING_WEEK_ITERATIONS =
  "ERROR_OCCURED_WHILE_FETCHING_WEEK_ITERATIONS";

export const RESET_CURRENT_WEEK_ITERATION_CREATED =
  "RESET_CURRENT_WEEK_ITERATION_CREATED";

export const BEGIN_WEEK_ITERATION_CREATION = "BEGIN_WEEK_ITERATION_CREATION";
export const WEEK_ITERATION_CREATED_SUCCESSFULLY =
  "WEEK_ITERATION_CREATED_SUCCESSFULLY";
export const WEEK_ITERATION_CREATION_FAILED = "WEEK_ITERATION_CREATION_FAILED";
export const ERROR_OCCURRED_ON_CREATING_WEEK_ITERATION =
  "ERROR_OCCURRED_ON_CREATING_WEEK_ITERATION";

export const SETUP_WEEK_ITERATIONS_FORM = "SETUP_WEEK_ITERATIONS_FORM";

/* END - WEEK ITERATIONS ***************************************************************************************/

/* START - ACTUAL TERMS ***************************************************************************************/

export const START_FETCHING_ACTUAL_TERMS = "START_FETCHING_ACTUAL_TERMS";
export const FETCHING_ACTUAL_TERMS_SUCCESSFUL =
  "FETCHING_ACTUAL_TERMS_SUCCESSFUL";
export const FETCHING_ACTUAL_TERMS_EMPTY_RESULT_SET =
  "FETCHING_ACTUAL_TERMS_EMPTY_RESULT_SET";
export const ERROR_OCCURED_WHILE_FETCHING_ACTUAL_TERMS =
  "ERROR_OCCURED_WHILE_FETCHING_ACTUAL_TERMS";

export const SETUP_ACTUAL_TERMS_FORM = "SETUP_ACTUAL_TERMS_FORM";

export const RESET_CURRENT_ACTUAL_TERM_CREATED =
  "RESET_CURRENT_ACTUAL_TERM_CREATED";

export const BEGIN_ACTUAL_TERM_CREATION = "BEGIN_ACTUAL_TERM_CREATION";
export const ACTUAL_TERM_CREATED_SUCCESSFULLY =
  "ACTUAL_TERM_CREATED_SUCCESSFULLY";
export const ACTUAL_TERM_CREATION_FAILED = "ACTUAL_TERM_CREATION_FAILED";
export const ERROR_OCCURRED_ON_CREATING_ACTUAL_TERM =
  "ERROR_OCCURRED_ON_CREATING_ACTUAL_TERM";

/* END - ACTUAL TERMS ***************************************************************************************/

/* START - ACTUAL WEEKS ***************************************************************************************/

export const START_FETCHING_YEARS_WEEKS = "START_FETCHING_YEARS_WEEKS";
export const FETCHING_YEARS_WEEKS_SUCCESSFUL =
  "FETCHING_YEARS_WEEKS_SUCCESSFUL";
export const FETCHING_YEARS_WEEKS_EMPTY_RESULT_SET =
  "FETCHING_YEARS_WEEKS_EMPTY_RESULT_SET";
export const ERROR_OCCURED_WHILE_FETCHING_YEARS_WEEKS =
  "ERROR_OCCURED_WHILE_FETCHING_YEARS_WEEKS";

export const SETUP_ACTUAL_WEEKS_FORM = "SETUP_ACTUAL_WEEKS_FORM";

export const RESET_CURRENT_ACTUAL_WEEK_CREATED =
  "RESET_CURRENT_ACTUAL_WEEK_CREATED";

export const BEGIN_ACTUAL_WEEK_CREATION = "BEGIN_ACTUAL_WEEK_CREATION";
export const ACTUAL_WEEK_CREATED_SUCCESSFULLY =
  "ACTUAL_WEEK_CREATED_SUCCESSFULLY";
export const ACTUAL_WEEK_CREATION_FAILED = "ACTUAL_WEEK_CREATION_FAILED";
export const ERROR_OCCURRED_ON_CREATING_ACTUAL_WEEK =
  "ERROR_OCCURRED_ON_CREATING_ACTUAL_WEEK";
