export const TOGGLE_MODAL_DISPLAY = "TOGGLE_MODAL_DISPLAY";
export const SETUP_CLASS_LEVEL_FORM = "SETUP_CLASS_LEVEL_FORM";

export const BEGIN_CLASS_LEVEL_CREATION = "BEGIN_CLASS_LEVEL_CREATION";
export const CLASS_LEVEL_CREATED_SUCCESSFULLY =
  "CLASS_LEVEL_CREATED_SUCCESSFULLY";
export const CLASS_LEVEL_CREATION_FAILED = "CLASS_LEVEL_CREATION_FAILED";
export const ERROR_OCCURRED_ON_CREATING_CLASS_LEVEL =
  "ERROR_OCCURRED_ON_CREATING_CLASS_LEVEL";
