export const STUDENT_REGISTRATION_SUCCESSFUL = 'STUDENT_REGISTRATION_SUCCESSFUL';
export const STUDENT_REGISTRATION_FAILED = 'STUDENT_REGISTRATION_FAILED';
export const ERROR_WHILE_REGISTERING_STUDENT = 'ERROR_WHILE_REGISTERING_STUDENT';


export const FEE_PAYMENT_SUCCESSFUL = 'FEE_PAYMENT_SUCCESSFUL';
export const FEE_PAYMENT_FAILED = 'FEE_PAYMENT_FAILED';
export const ERROR_OCCURRED_WHILE_PAYING_FEE = 'ERROR_OCCURRED_WHILE_PAYING_FEE';
