export const STUDENT_REGISTRATION_SUCCESSFUL = 'STUDENT_REGISTRATION_SUCCESSFUL';
export const STUDENT_REGISTRATION_FAILED = 'STUDENT_REGISTRATION_FAILED';
export const ERROR_WHILE_REGISTERING_STUDENT = 'ERROR_WHILE_REGISTERING_STUDENT';
