export const STUDENT_REGISTRATION_SUCCESSFUL = 'STUDENT_REGISTRATION_SUCCESSFUL';
export const STUDENT_REGISTRATION_FAILED = 'STUDENT_REGISTRATION_FAILED';
export const ERROR_WHILE_REGISTERING_STUDENT = 'ERROR_WHILE_REGISTERING_STUDENT';


export const FEE_PAYMENT_SUCCESSFUL = 'FEE_PAYMENT_SUCCESSFUL';
export const FEE_PAYMENT_FAILED = 'FEE_PAYMENT_FAILED';
export const ERROR_OCCURRED_WHILE_PAYING_FEE = 'ERROR_OCCURRED_WHILE_PAYING_FEE';

export const STUDENTS_FETCHED_SUCCESSFULLY = 'STUDENTS_FETCHED_SUCCESSFULLY';
export const STUDENTS_FETCHED_EMPTY_RESULT_SET = 'STUDENTS_FETCHED_EMPTY_RESULT_SET';
export const ERROR_OCCURRED_WHILE_FETCHING_STUDENTS = 'ERROR_OCCURRED_WHILE_FETCHING_STUDENTS';


export const STUDENT_FEE_STATEMENT_FETCHED_SUCCESSFULLY = 'STUDENT_FEE_STATEMENT_FETCHED_SUCCESSFULLY';
export const STUDENT_FEE_STATEMENT_FETCHED_EMPTY_RESULT_SET = 'STUDENT_FEE_STATEMENT_FETCHED_EMPTY_RESULT_SET';
export const ERROR_OCCURRED_WHILE_FETCHING_STUDENT_FEE_STATEMENT = 'ERROR_OCCURRED_WHILE_FETCHING_STUDENT_FEE_STATEMENT';

