export const REGISTER_COMPANY_BRANCHES_FORM = "REGISTER_COMPANY_BRANCHES_FORM";
export const REGISTER_SYSTEM_USERS_FORM = "REGISTER_SYSTEM_USERS_FORM";
export const REGISTER_EMPLOYMENT_CATEGORIES_FORM = "REGISTER_EMPLOYMENT_CATEGORIES_FORM";
