export const START_CREATING_A_COMPANY_BRANCH =
  "START_CREATING_A_COMPANY_BRANCH";
export const COMPANY_BRANCH_CREATED_SUCCESSFULLY =
  "COMPANY_BRANCH_CREATED_SUCCESSFULLY";
export const COMPANY_BRANCH_CREATION_FAILED = "COMPANY_BRANCH_CREATION_FAILED";

export const START_FETCHING_A_COMPANY_OWNERS_COMPANY_DETAILS =
  "START_FETCHING_A_COMPANY_OWNERS_COMPANY_DETAILS";
export const FETCHING_COMPANY_OWNERS_COMPANY_DETAILS_SUCCEEDED =
  "FETCHING_COMPANY_OWNERS_COMPANY_DETAILS_SUCCEEDED";
export const FETCHING_COMPANY_OWNERS_COMPANY_DETAILS_FAILED =
  "FETCHING_COMPANY_OWNERS_COMPANY_DETAILS_FAILED";
export const FETCHING_COMPANY_OWNERS_COMPANY_DETAILS_EMPTY_RESULT_SET =
  "FETCHING_COMPANY_OWNERS_COMPANY_DETAILS_EMPTY_RESULT_SET";

export const START_FETCHING_A_COMPANYS_BRANCHES =
  "START_FETCHING_A_COMPANYS_BRANCHES";
export const FETCHING_THE_COMPANYS_BRANCHES_SUCCEEDED =
  "FETCHING_THE_COMPANYS_BRANCHES_SUCCEEDED";
export const FETCHING_THE_COMPANYS_BRANCHES_FAILED =
  "FETCHING_THE_COMPANYS_BRANCHES_FAILED";
export const FETCHING_THE_COMPANYS_BRANCHES_EMPTY_RESULT_SET =
  "FETCHING_THE_COMPANYS_BRANCHES_EMPTY_RESULT_SET";

export const START_REGISTERING_A_SYSTEM_USER =
  "START_REGISTERING_A_SYSTEM_USER";
export const SYSTEM_USER_REGISTRATION_SUCCESSFUL =
  "SYSTEM_USER_REGISTRATION_SUCCESSFUL";
export const SYSTEM_USER_REGISTRATION_FAILED =
  "SYSTEM_USER_REGISTRATION_FAILED";

export const START_REGISTERING_EMPLOYMENT_CATEGORIES =
  "START_REGISTERING_EMPLOYMENT_CATEGORIES";
export const EMPLOYMENT_CATEGORIES_REGISTRATION_SUCCESSFUL =
  "EMPLOYMENT_CATEGORIES_REGISTRATION_SUCCESSFUL";
export const EMPLOYMENT_CATEGORIES_REGISTRATION_FAILED =
  "EMPLOYMENT_CATEGORIES_REGISTRATION_FAILED";

export const RESET_CURRENT_BRANCH_CREATED_SUCCESSFULLY =
  "RESET_CURRENT_BRANCH_CREATED_SUCCESSFULLY";

export const START_FETCHING_A_COMPANYS_SYSTEM_USERS =
  "START_FETCHING_A_COMPANYS_SYSTEM_USERS";
export const FETCHING_THE_COMPANYS_SYSTEM_USERS_SUCCEEDED =
  "FETCHING_THE_COMPANYS_SYSTEM_USERS_SUCCEEDED";
export const FETCHING_THE_COMPANYS_SYSTEM_USERS_FAILED =
  "FETCHING_THE_COMPANYS_SYSTEM_USERS_FAILED";
export const FETCHING_THE_COMPANYS_SYSTEM_USERS_EMPTY_RESULT_SET =
  "FETCHING_THE_COMPANYS_SYSTEM_USERS_EMPTY_RESULT_SET";

export const RESET_CURRENT_SYSTEM_USER_CREATED_SUCCESSFULLY =
  "RESET_CURRENT_SYSTEM_USER_CREATED_SUCCESSFULLY";

export const START_FETCHING_A_COMPANYS_EMPLOYMENT_CATEGORIES =
  "START_FETCHING_A_COMPANYS_EMPLOYMENT_CATEGORIES";
export const FETCHING_THE_COMPANYS_EMPLOYMENT_CATEGORIES_SUCCEEDED =
  "FETCHING_THE_COMPANYS_EMPLOYMENT_CATEGORIES_SUCCEEDED";
export const FETCHING_THE_COMPANYS_EMPLOYMENT_CATEGORIES_FAILED =
  "FETCHING_THE_COMPANYS_EMPLOYMENT_CATEGORIES_FAILED";
export const FETCHING_THE_COMPANYS_EMPLOYMENT_CATEGORIES_EMPTY_RESULT_SET =
  "FETCHING_THE_COMPANYS_EMPLOYMENT_CATEGORIES_EMPTY_RESULT_SET";

export const RESET_EMPLOYMENT_CATEGORY_CREATION_FLAG =
  "RESET_EMPLOYMENT_CATEGORY_CREATION_FLAG";
