apiVersion: v1
kind: Service
metadata:
  name: kopa-react-client
  namespace: uat
  labels:
    app: kopa-react-client
    name: kopa-react-client
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 80
  selector:
    app: kopa-react-client
    name: kopa-react-client
