export const ENTIRE_SCHOOL_ANNOUNCEMENT_TYPE = "ENTIRE_SCHOOL_ANNOUNCEMENT_TYPE";
export const SPECIFIC_CLASS_ANNOUNCEMENT_TYPE = "SPECIFIC_CLASS_ANNOUNCEMENT_TYPE";
export const SPECIFIC_STREAM_ANNOUNCEMENT_TYPE = "SPECIFIC_STREAM_ANNOUNCEMENT_TYPE";
