export const REGISTER_A_STUDENT_PAGE = "REGISTER_A_STUDENT_PAGE";
export const PAY_FEE = "PAY_FEE";
export const SEND_HOME_FROM_ENTIRE_SCHOOL = "SEND_HOME_FROM_ENTIRE_SCHOOL";
export const SEND_HOME_PER_CLASS = "SEND_HOME_PER_CLASS";
export const CORRECT_STUDENT_PERSONAL_DETAILS = "CORRECT_STUDENT_PERSONAL_DETAILS";
export const CHANGE_STUDENT_RESIDENCE = "CHANGE_STUDENT_RESIDENCE";
