export const LOGIN_ACCESS_PRIVILEGE = 1;
export const REGISTER_A_STUDENT_ACCESS_PRIVILEGE = 2;
export const CORRECT_A_STUDENT_PERSONAL_DETAILS_ACCESS_PRIVILEGE = 3;
export const REGISTER_A_FEE_INSTALLMENT_ACCESS_PRIVILEGE = 4;
export const CORRECT_A_FEE_PAYMENT_ACCESS_PRIVILEGE = 5;
export const DELETE_A_STUDENT_ACCESS_PRIVILEGE = 6;
export const CHANGE_A_STUDENT_RESIDENCE_ACCESS_PRIVILEGE = 7;
